= Overview

This page provides a high-level overview of how to get started using ContentLib.

By following the "Next Steps" link at the bottom of each page,
you will be guided through the process of setting up your mod,
creating a custom item,
creating a recipe to produce that item with,
and a milestone  (schematic) to unlock the recipe.

== ContentLib Workflow

ContentLib mod allows users to easily create custom
recipes, items, schematics, and more, or modify existing ones from any mod!
Custom content of your own design is only a couple of JSON files away!

The flow of developing a ContentLib script is generally as follows.
Don't worry, futher tutorial pages will walk you through these steps in more detail.

1. Get an idea for what you want to modify
2. https://ficsit.app/mod/ContentLib[Install ContentLib in your game client via SMM]
3. Follow the directions on the xref:Tutorials/Setup.adoc[Setup page] to get a mod skeleton ready
4. Locate the asset names of what you would like to modify or unlock. The xref:Tutorials/FindAssetPath.adoc[Finding Assets] tutorial will help with this
5. Follow the directions on the docs' Tutorials page for the asset you'd like to create, tweaking the examples to reach your end goal
    * If you want to *modify the properties of an existing asset,*
      you'll want to create a xref:Features/Patching.adoc[Patch for that asset]
    * If you want to *create a new item or fluid* to use in recipes,
      follow xref:Tutorials/CreateItem.adoc[Create an Item]
    * If you want to *create a new recipe* for producing an item or building,
      follow xref:Tutorials/CreateRecipe.adoc[Create a Recipe]
    * If you want to *create new ways to unlock recipes or buildings*,
      follow xref:Tutorials/CreateRecipe.adoc[Create a Schematic]
6. Use your text editor's auto suggest (powered by xref:Reference/JsonSchema.adoc[JSON Schemas])
  to learn about and utilize fields that the tutorials may not cover
7. If something isn't working, follow the xref:Tutorials/Troubleshooting.adoc[Troubleshooting directions] to figure out what went wrong and how to resolve it

If you get stuck, please describe your goal
and share your script(s) as a file upload on the https://discord.gg/kcRmFxn89d[Nog's Mods discord server].

== Next Steps

Follow the directions on the xref:Tutorials/Setup.adoc[Setting Up page]
to get a basic structure for your scripts and mod.
