= Publish your Mod

TODO

You don't necessarily need to set up a full modding project (Unreal editor install), but it helps a lot since it will package your mod for you, and it will make it easier to transition to a full mod later, if you so desire.

== Copied in markdown

=== Option 1 - No Unreal Editor

Before you start this section, I highly suggest going with Option 2 instead, since it makes it a lot easier to ensure the folder structure is correct, and helps if you ever decide to go further in modding.

Simply start out with this template plugin and edit the files to match your needs TODO.

Put the folder in the `/Mods/` folder of your Satisfactory game install and rename it to the [Mod Reference](https://docs.ficsit.app/satisfactory-modding/latest/Development/BeginnersGuide/index.html#_mod_reference) you want to use for your mod. Be sure to view the linked page to see what characters are supported in mod references.

Then rename the `.uplugin` file inside the folder to match the folder name (again, the mod reference).

TODO

Now continue below at "Moving in the scripts"

=== Option 2 - With Unreal Editor

You'll need to follow the normal modding setup docs [here](https://docs.ficsit.app/) to get a copy of the editor.

Create your plugin as normal as described on the docs.

Now continue below at the "Moving in the scripts" section. Your script files will go in your modding project's plugin folder. In order to package your changes for the game, and for distribution as a mod, use Alpakit as described in the docs.

You can still edit the json files in your `/Mods/` folder, but if you chose to do so, be careful not to accidentally lose their contents by packing over them with Alpakit.

== Moving in the scripts

Once you have decided to put your ContentLib scripts into a mod, you can move them out of your Configs folder and into the plugin folder for your mod.

Basically, copy the ContentLib subfolder from your Configs into your plugin's root directory. To be specific, they should now be in the following locations:

```?
/ModReferenceGoesHere/ContentLib/Items/
/ModReferenceGoesHere/ContentLib/Icons/
/ModReferenceGoesHere/ContentLib/Recipes/
/ModReferenceGoesHere/ContentLib/RecipePatches/
/ModReferenceGoesHere/ContentLib/ItemPatches/
/ModReferenceGoesHere/ContentLib/Schematics/
/ModReferenceGoesHere/ContentLib/SchematicPatches/
/ModReferenceGoesHere/ContentLib/VisualKits/
/ModReferenceGoesHere/ContentLib/CDOs/
```











Make sure that you list `ContentLib` as a required dependency of your own mod, and follow the directions [here](https://docs-dev.ficsit.app/satisfactory-modding/latest/Development/BeginnersGuide/Adding_Ingame_Mod_Icon.html) to be sure that any json files you include in your mod files get packed into your final mod.


Follow the directions https://docs.ficsit.app/satisfactory-modding/latest/Development/BeginnersGuide/index.html[here] to get the modding environment set up and create a plugin directory to use for your mod. You can stop once you've completed the "Plugin Setup and Init Game World" section.

You should use the `PluginSettings.ini` 'AdditionalNonUSFDirectories' directive to ensure that this folder is packaged with your mod, see the directions https://docs.ficsit.app/satisfactory-modding/latest/Development/BeginnersGuide/Adding_Ingame_Mod_Icon.html#_setup[here] regarding adding a mod icon to learn how. Simply add another line for the ContentLib folder.

Example `PluginSettings.ini`

```
[StageSettings]
+AdditionalNonUSFDirectories=Resources
+AdditionalNonUSFDirectories=ContentLib

```


This process is out of scope of this tutorial. You can follow the directions in the [modding documentation](https://docs.ficsit.app/satisfactory-modding/latest/UploadToSMR.html) for uploading to Satisfactory Mod Repository.

A couple things to note

- Made sure you followed the directions above for including 