= Publish your Mod

This page directs you to the correct docs for how to publish ContentLib scripts you have created as mod for others to use.

Check out the 
xref:Tutorials/Setup.adoc[Setup document]
to set up a plugin structure for your mod files.

== Upload to SMR

If you followed the xref:Tutorials/Setup.adoc[Setup document]'s "Example Plugin Skeleton" approach
your files should already be in mod format.

However, if you used the "Configs Folder" approach, you will need to go back and set up the
xref:Tutorials/Setup.adoc#DownloadSkeleton[Example Plugin Skeleton].
Remember to move your old ContentLib files out of the config folder when testing your new mod skeleton!

Once you have edited the skeleton to match your needs,
you're ready to upload your mod to Satisfactory Mod Repository for anyone to download and use.
You can follow the directions in the
https://docs.ficsit.app/satisfactory-modding/latest/UploadToSMR.html[main modding documentation]
to achieve this.

Make sure your mod uplugin specifies ContentLib as a dependency as described in the 
xref:Tutorials/Setup.adoc[Setup document]
or your mod won't do anything!
If you used the skeleton, it should already depend on ContentLib.
