= Troubleshooting

[NOTE]
====
This page is still a work in progress. It currently consists of two sets of troubleshooting directions I wrote up in the past. Please be patient while I improve the docs.
====

Although ContentLib is generally easier to use than setting up stuff in the Unreal editor,
there is still room for mistakes.
You should follow the steps below to set up for debugging your scripts.

If an error is encountered while loading, the mod will print error information to the SML console and your log files.

- Launch your game with the `-logs` flag so you can see the debug console while the game is running.
  Find out how to do this https://docs.ficsit.app/satisfactory-modding/latest/Development/ModLoader/Logging.html#_viewing_logs[here].
- It can be beneficial to open the `FactoryGame.log` file in a text editor that has good searching capabilities,
  such as Notepad++, so you can track down messages.
  The file is stored in your `%localappdata%` folder,
  for example, `<your user dir path>\AppData\Local\FactoryGame\Saved\Logs\FactoryGame.log`
- You should get the **Content Inspector** mod
  to check if your content has loaded correctly,
  and to discover values and paths of base game and mod assets.
  More info xref:Tutorials/ContentInspector.adoc[here].
- Increase your Logging Detail Level to either
  `Warnings and Info` or `Debug` in the Mod Configs screen for ContentLib

Once you have these tools set up, the following tips/process should help you debug.

- Check the logs for WARNING and ERROR level messages with the `LogContentLib` category,
  or containing the text `[CL]`, these contain potentially useful messages.
  More info on the xref:BackgroundInfo/Logging.adoc[Logging page].
- Use Content Inspector (mentioned above) to check the data for loaded items and see if it matches what you expect

See xref:Tutorials/ContentInspector.adoc[Using ContentInspector] for how to check if your content is loaded or not without having to poke around in-game.

== Hot Reloading Disclaimer

Although ContentLib attempts to offer live reloading of JSON assets
(when triggered by the chat commands or config widget) this hasn't really been tested much,
and Satisfactory was not designed for it.
You should probably fully re-launch the game to test if you're having trouble with assets showing up.
Hopefully this will improve in the future.

== Frequent Problems

* I created a new Item but it doesn't exist in*game
  ** Remember that you need to have a Recipe that produces that item, and a Schematic to unlock that item, for it to exist in*game.
  ** Check the logs as mentioned above to see if there were any errors in registering it
  ** Make sure that you put your files in the correct folders. See the xref:BackgroundInfo/FolderNames.adoc[Folder Names] section.
* I wrote a Patch, but it isn't changing anything!
  ** Check the logs as mentioned above to see if there were any errors in registering it
  ** Make sure that you put your files in the correct folders. See the xref:BackgroundInfo/FolderNames.adoc[Folder Names] section.
