= Using ContentLib APIs in Your Mod

In order to use ContentLib's libraries,
you'll have to obtain a copy of the ContentLib plugin source code and add it to your copy of the project.

== Obtain the ContentLib Source Code

First off, you need to clone the
https://github.com/Nogg-aholic/ContentLib[ContentLib] plugin source code
and add it to your own Starter Project's Plugins folder.
It should be side by side with your own mod's plugin folder,
and the name of the folder should be exactly `ContentLib`.

Make sure there are no extra folders in between.

If you'd like to test if this works,
https://docs.ficsit.app/satisfactory-modding/latest/Development/BeginnersGuide/project_setup.html#_generate_visual_studio_files[regenerate visual studio build files]
and build for development editor in Visual Studio.

The build should succeed without errors, and you should be able to open the editor and make calls to
xref:Reference/BpLib.adoc[ContentLib blueprint functions].

== Setting up the Plugin Dependencies

Follow the xref:Tutorials/PublishMod.adoc[Publish your Work] tutorial
to get dependencies set up correctly
so that your mod uplugin's "Plugins" sections contains both SML and ContentLib as dependencies.

Example: `ModReference.uplugin`
[source, json]
----
"Plugins": [
	{
		"Name": "SML",
		"Enabled": true,
		"SemVersion": "^3.3.2"
	},
	{
		"Name": "ContentLib",
		"Enabled": true,
		"SemVersion": "^1.0.0"
	}
]
----

[WARNING]
====
The version numbers in the above examples are not necessarily correct.
Make sure that you're using the latest versions of SML and ContentLib.
====

== Next Steps

If you're only planning on using Blueprint functions, you should be good to go.
However, {cpp} usage requires xref:Reference/CppLib.adoc[a few more steps].
