= Automatic Name Resolving

In an effort to cut down on the verbosity required when writing ContentLib files, many fields will try to automatically resolve shortenings into their full version.

For example, you can use the name `Coal` to refer to the Coal item, in place of the fully qualified asset path ``.

Items are resolved by comparing the supplied Item name against existing Item ClassNames in the game. The first match the mod finds will be used.

Watch out for ambiguity with Class Names! Sometimes items can have very similar names. Be as specific as possible with the name to avoid problems with this. You can use xref:Tutorials/ContentInspector.adoc[ContentInspector] to find out what class a path actually resolved to.

Class Names have a `_C` suffix when they have been generated by a Blueprint. The `_C` suffix, as well as the naming-convention related `Build_` or `Desc_` prefix, is optional for this mod. That being said, in some cases, you *must* include the prefixes, such as `Build_`, in order to distinguish between assets that otherwise all match the query. For example, the name "ConstructorMk1" would match the following assets:

- The FGBuildableManufacturer `/Game/FactoryGame/Buildable/Factory/ConstructorMk1/Build_ConstructorMk1`
- The FGBuildingDescriptor `/Game/FactoryGame/Buildable/Factory/ConstructorMk1/Desc_ConstructorMk1`
- The FGRecipe `/Game/FactoryGame/Buildable/Factory/ConstructorMk1/Recipe_ConstructorMk1`
- The FGDecorationTemplate `/Game/FactoryGame/Buildable/Factory/ConstructorMk1/Deco_ConstructorMk1`

In this cause, you must include the prefix in order to specify which of these assets you're referring to.
